# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b668057c676f6b188d624ed3ceb1f1079051a69e5904dab5a4a692322f4c738bd035d399a1a5ad283925c306e03cb689b36f4a09cba542e64630c9c262c05e6

test:
  secret_key_base: 0a14026dbeef4273f9dd9929b18765dd41f809bb46eb71cb2cde0903153389eb4bd898d29de1bcdbbd33f3c8551859e6bd490a7b162acb7e8898f3b5ed2de4ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
